trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Angular App'
  steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      addToPath: true

  - script: |
      cd apporderingsystem-angular
      npm install --force
      ng build --configuration=production
    displayName: 'Build Angular App'

  - task: CopyFiles@2
    inputs:
      sourceFolder: 'apporderingsystem-angular/dist'
      targetFolder: '$(Build.ArtifactStagingDirectory)/angular-dist'
    displayName: 'Copy Angular Dist Files'

- job: Deploy
  displayName: 'Deploy Angular App'
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.ArtifactStagingDirectory)/angular-dist'
      targetFolder: '$(Build.ArtifactStagingDirectory)/wwwroot'
    displayName: 'Copy Angular Dist Files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/wwwroot'
      artifactName: 'angular-dist'
      publishLocation: 'Container'

- job: DeployToAzure
  displayName: 'Deploy to Azure App Service'
  dependsOn: Deploy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'appServiceConnection'
      appType: 'webAppLinux'
      WebAppName: 'appinventory'
      packageForLinux: '$(Pipeline.Workspace)/angular-dist'
      enableCustomDeployment: true


