trigger:
- main  # Cambia esto si tu rama principal tiene un nombre diferente

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Publish Artifact'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      cd apporderingsystem-angular
      npm install --force
      npm run build --configuration=production
    displayName: 'Build Angular App'

  - publish: $(System.DefaultWorkingDirectory)/apporderingsystem-angular/APPVIRTUALSTORE
    artifact: AngularApp
    displayName: 'Publish Angular App Artifact'

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - download: current
    artifact: AngularApp
    displayName: 'Download Angular App Artifact'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'appServiceConnection'
      appType: 'webApp'
      WebAppName: 'appinventory'
      packageForLinux: '$(Pipeline.Workspace)/AngularApp/APPVIRTUALSTORE'
    displayName: 'Deploy to Azure App Service'