# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Windows pool DEV

jobs:
- job: Build_And_Deploy_Angular
  displayName: 'Build and Deploy Angular'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      cd $(Build.SourcesDirectory)/apporderingsystem-angular
      npm install -g @angular/cli
      npm install --force
      ng build --configuration=production
    displayName: 'npm install and build'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/apporderingsystem-angular/dist/APPVIRTUALSTORE'
      artifact: 'angular-dist'
      publishLocation: 'pipeline'

- job: Deploy_Angular
  displayName: 'Deploy Angular App'
  dependsOn: Build_And_Deploy_Angular
  pool:
    vmImage: 'ubuntu-latest'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: '$(System.TeamProject)'
      definition: '$(System.DefinitionId)'
      buildVersionToDownload: 'latest'
      pipelineId: '$(System.TeamProject)/$(Build.DefinitionName)'
      artifactName: 'angular-dist'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'appServiceConnection'
      appType: 'webAppLinux'
      WebAppName: 'appinventory'
      packageForLinux: '$(System.ArtifactsDirectory)/angular-dist/**/*.zip'
      runtimeStack: 'NODE|14.x'
