# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - appfront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build .NET Core app
        run: |
          cd API-INVENTARIO-main
          dotnet build --configuration Release

      - name: Publish .NET Core app
        run: |
          cd API-INVENTARIO-main
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload .NET Core artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Build Angular app
        run: |
          cd apporderingsystem-angular
          npm install --force
          npm run build

      - name: Upload Angular artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: apporderingsystem-angular/dist

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: angular-app  # Solo descargamos el artefacto de Angular

      - name: Deploy Angular to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'appfront'
          slot-name: 'Production'
          package: . # Especificamos la ruta del artefacto Angular
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B7B9CA1F44934D519867D58BB44B6BA7 }}